server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moyun?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
  
  # MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.moyun.entity
  configuration:
    map-underscore-to-camel-case: true

# 日志配置
logging:
  level:
    com.moyun: info
    org.springframework.web: warn
  file:
    name: ./logs/moyun.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 文件上传配置
file:
  upload:
    path: ./uploads/
    max-size: 10MB
    allowed-types: jpg,jpeg,png,gif,pdf,doc,docx

# 安全配置
security:
  jwt:
    secret: moyun-jwt-secret-key-2024
    expiration: 86400000 # 24小时 